transform:
    target: main
    outputs:
        local:
            type: postgres
            host: localhost
            port: 5432
            user: user
            pass: pass
            threads: 1
            dbname: analytics
            schema: stage

        main:
            type: redshift
            host: remotehost
            port: 5439
            user: user
            pass: pass
            threads: 4
            dbname: analytics
            schema: stage
