version: "3.8"

services:
  scipy:
    container_name: jupyter-notebook
    image: jupyter/scipy-notebook:2023-08-21
    environment:
      - JUPYTER_TOKEN=secret
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    restart: unless-stopped
