version: 2

models:
 - name: purchase_order_resume
   columns:
    - name: purchaseorder
    - name: purchaseordertype
    - name: purchaseordersubtype
    - name: supplier
    - name: documentcurrency
    - name: PurgReleaseTimeTotalAmount
    - name: id_erp_order_item
    - name: order_number
    - name: order_item
    - name: id_project        
    - name: partner_code
    - name: contract_number
    - name: order_price
    - name: pr
    - name: id_item
    - name: item_description    