name: Release Charts

on:
    # push:
    #     branches:
    #         - main

    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "debug"
                type: choice
                options:
                    - warning
                    - info
                    - debug
            print_tags:
                description: "Print tags"
                required: true
                default: true
                type: boolean

jobs:
    release:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

            - name: Install Helm
              uses: azure/setup-helm@v3

            - name: Release Charts
              uses: helm/chart-releaser-action@v1.5.0
              env:
                  CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
